insert into adresses (adress_name) values('Bektemir');
insert into adresses (adress_name) values('Olmazor');
insert into adresses (adress_name) values('Mirobod');
insert into adresses (adress_name) values('Oqoltin');
insert into adresses (adress_name) values('Shumanay');
insert into adresses (adress_name) values('Xojayli');
insert into adresses (adress_name) values('Xonqa');
insert into adresses (adress_name) values('Shovot');
insert into adresses (adress_name) values('Vobkent');
insert into adresses (adress_name) values('Kitob');
insert into adresses (adress_name) values('Jarariq');
insert into adresses (adress_name) values('Jasliq');
insert into adresses (adress_name) values('Xiva');
insert into adresses (adress_name) values('Buxoro');
insert into adresses (adress_name) values('Andijon');
insert into adresses (adress_name) values('Yangiyol');
insert into adresses (adress_name) values('Chinoz');
insert into adresses (adress_name) values('Qarshi');
insert into adresses (adress_name) values('Samarqand');
insert into adresses (adress_name) values('Olot');
insert into adresses (adress_name) values('Kogon');
insert into adresses (adress_name) values('Shofirkon');
insert into adresses (adress_name) values('Ishtihon');
insert into adresses (adress_name) values('Oqtosh');
insert into adresses (adress_name) values('Ziyodin');
insert into adresses (adress_name) values('Chimboy');
insert into adresses (adress_name) values('Xadra');
insert into adresses (adress_name) values('Paxtachi');
insert into adresses (adress_name) values('Guzar');
insert into adresses (adress_name) values('Dalaguzar');




insert into users (fio, position, adress_id) values ('Ulrikaumeko Baptista', 'Account Representative I', 1);
insert into users (fio, position, adress_id) values ('Cointon Penswick', 'Administrative Officer', 2);
insert into users (fio, position, adress_id) values ('Shelba Haugh', 'Legal Assistant', 3);
insert into users (fio, position, adress_id) values ('Flynn Francescuccio', 'Research Assistant IV', 4);
insert into users (fio, position, adress_id) values ('Cody Durgan', 'Dental Hygienist', 5);
insert into users (fio,  position, adress_id) values ('Cairistiona Hedylstone', 'Recruiter', 7);
insert into users (fio, position, adress_id) values ('Dede Utteridge', 'Administrative Assistant IV', 8);
insert into users (fio, position, adress_id) values ('Shannon Gregor', 'Automation Specialist II', 9);
insert into users (fio, position, adress_id) values ('Reube Trayhorn', 'Geologist I', 10);
insert into users (fio, position, adress_id) values ('Mannie Hounson', 'Environmental Tech', 11);
insert into users (fio, position, adress_id) values ('Cynthie Dearn', 'Senior Sales Associate', 12);
insert into users (fio, position, adress_id) values ('Martainn Penhearow', 'Geologist II', 13);
insert into users (fio, position, adress_id) values ('Humberto Robey', 'Account Executive', 14);
insert into users (fio, position, adress_id) values ('Jemie Howgill', 'Account Coordinator', 15);
insert into users (fio, position, adress_id) values ('Ottilie Chumley', 'Sales Associate', 16);
insert into users (fio, position, adress_id) values ('Gigi Tythacott', 'VP Marketing', 17);
insert into users (fio, position, adress_id) values ('Marcelline Dury', 'Legal Assistant', 18);
insert into users (fio, position, adress_id) values ('Gabbie Aingell', 'Actuary', 19);
insert into users (fio, position, adress_id) values ('Dori Trevear', 'Environmental Specialist', 20);
insert into users (fio, position, adress_id) values ('Ketti Elgy', 'Database Administrator I', 21);
insert into users (fio, position, adress_id) values ('Reeba Gwilym', 'Administrative Assistant III', 22);
insert into users (fio, position, adress_id) values ('Hilton Tanti', 'Structural Analysis Engineer', 23);
insert into users (fio, position, adress_id) values ('Margarete Locksley', 'Senior Developer', 24);
insert into users (fio, position, adress_id) values ('Rowan Dami', 'Engineer I', 25);
insert into users (fio, position, adress_id) values ('Pyotr Sowerbutts', 'Mechanical Systems Engineer', 26);
insert into users (fio, position, adress_id) values ('Baird Gavagan', 'Sales Associate', 27);
insert into users (fio, position, adress_id) values ('Blondie Kreber', 'Environmental Specialist', 28);
insert into users (fio, position, adress_id) values ('Gustavo Craigheid', 'Technical Writer', 29);
insert into users (fio, position, adress_id) values ('Kliment Yakovlev', 'Administrative Assistant II', 30);
insert into users (fio, position, adress_id) values ('Keene Passion', 'Design Engineer', 31);
insert into users (fio, position, adress_id) values ('Ozzie Curme', 'Biostatistician III', 32);
insert into users (fio, position, adress_id) values ('Izaak Newlyn', 'Web Developer II', 33);
insert into users (fio, position, adress_id) values ('Irma Cassie', 'Human Resources Assistant III', 34);
insert into users (fio, position, adress_id) values ('Kelly Vasyuchov', 'Help Desk Technician', 35);
insert into users (fio, position, adress_id) values ('Dunc Ubsdall', 'Environmental Tech', 36);
insert into users (fio, position, adress_id) values ('Kingston Peterken', 'Accountant I', 37);
insert into users (fio, position, adress_id) values ('Wyatan Cabel', 'Data Coordiator', 38);
insert into users (fio, position, adress_id) values ('Herbie Refford', 'Sales Representative', 39);
insert into users (fio, position, adress_id) values ('Clea Fullman', 'Assistant Professor', 40);
insert into users (fio, position, adress_id) values ('Petronilla Fackrell', 'Sales Representative', 41);
insert into users (fio, position, adress_id) values ('Indira Roon', 'Engineer III', 42);
insert into users (fio, position, adress_id) values ('Sukey Romanski', 'Human Resources Manager', 43);
insert into users (fio, position, adress_id) values ('Rozalie Duddle', 'Registered Nurse', 44);
insert into users (fio, position, adress_id) values ('Josefina Jaquest', 'Nurse Practicioner', 45);
insert into users (fio, position, adress_id) values ('Lazare Call', 'Help Desk Technician', 32);
insert into users (fio, position, adress_id) values ('Reginauld Hollyland', 'Project Manager', 13);
insert into users (fio, position, adress_id) values ('Robinson Morse', 'Statistician III', 32);
insert into users (fio, position, adress_id) values ('Emogene Petti', 'Social Worker', 21);
insert into users (fio, position, adress_id) values ('Celesta Sommerville', 'Administrative Assistant III', 10);
insert into users (fio, position, adress_id) values ('Ronna Luten', 'Research Associate', 9);
insert into users (fio, position, adress_id) values ('Irwinn McCuffie', 'Structural Analysis Engineer', 7);
insert into users (fio, position, adress_id) values ('Drusilla Aubrey', 'Design Engineer', 2);
insert into users (fio, position, adress_id) values ('Phil Corrao', 'Administrative Officer', 4);
insert into users (fio, position, adress_id) values ('Irvine Boots', 'Product Engineer', 5);
insert into users (fio, position, adress_id) values ('Lou Thurley', 'Geological Engineer', 5);
insert into users (fio, position, adress_id) values ('Grange Krates', 'VP Marketing', 21);
insert into users (fio, position, adress_id) values ('Bellina Ingyon', 'Electrical Engineer', 10);
insert into users (fio, position, adress_id) values ('Bertina Frayn', 'Senior Quality Engineer', 40);
insert into users (fio, position, adress_id) values ('Roland Legging', 'Paralegal', 23);
insert into users (fio, position, adress_id) values ('Barry Elcott', 'Human Resources Manager', 41);
insert into users (fio, position, adress_id) values ('Marion Buney', 'Chemical Engineer', 42);
insert into users (fio, position, adress_id) values ('Manon Quartermaine', 'Pharmacist', 33);
insert into users (fio, position, adress_id) values ('Carlee Vedstra', 'Systems Administrator II', 24);
insert into users (fio, position, adress_id) values ('Eve Silwood', 'Graphic Designer', 35);
insert into users (fio, position, adress_id) values ('Shellie Darkins', 'Marketing Manager', 16);
insert into users (fio, position, adress_id) values ('Sybilla Legrand', 'Web Designer I', 11);
insert into users (fio, position, adress_id) values ('Evvy Sliman', 'Assistant Professor', 13);
insert into users (fio, position, adress_id) values ('Joyous Gillbard', 'Internal Auditor', 9);
insert into users (fio, position, adress_id) values ('Ofilia Tomaskunas', 'Physical Therapy Assistant', 7);
insert into users (fio, position, adress_id) values ('Reginauld Simpson', 'Civil Engineer', 21);
insert into users (fio, position, adress_id) values ('Hubie Skells', 'Safety Technician III', 22);
insert into users (fio, position, adress_id) values ('Leslie Leech', 'Cost Accountant', 13);
insert into users (fio, position, adress_id) values ('Brandon Mathew', 'Food Chemist', 44);
insert into users (fio, position, adress_id) values ('Bernete Barles', 'Compensation Analyst', 25);
insert into users (fio, position, adress_id) values ('Greta Weaben', 'Payment Adjustment Coordinator', 16);
insert into users (fio, position, adress_id) values ('Bernhard Lundie', 'Senior Developer', 17);
insert into users (fio, position, adress_id) values ('Tybie Dome', 'Marketing Assistant', 28);
insert into users (fio, position, adress_id) values ('Thacher Baggs', 'Senior Developer', 39);
insert into users (fio, position, adress_id) values ('Leigh Claesens', 'Dental Hygienist', 40);
insert into users (fio, position, adress_id) values ('Courtnay Gemmill', 'Human Resources Assistant IV', 21);
insert into users (fio, position, adress_id) values ('Nikki MacCaughey', 'Senior Sales Associate', 32);
insert into users (fio, position, adress_id) values ('Padraic Skally', 'Senior Financial Analyst', 43);
insert into users (fio, position, adress_id) values ('Lurlene Cosley', 'Graphic Designer', 44);
insert into users (fio, position, adress_id) values ('Herrick Headington', 'Geological Engineer', 45);
insert into users (fio, position, adress_id) values ('Trev Lindman', 'Human Resources Assistant III', 36);
insert into users (fio, position, adress_id) values ('Abraham Planke', 'Help Desk Operator', 27);
insert into users (fio, position, adress_id) values ('Brnaby Veldens', 'Accountant IV', 18);
insert into users (fio, position, adress_id) values ('Sally Cornels', 'Product Engineer', 29);
insert into users (fio, position, adress_id) values ('Keefer Vasilyonok', 'Director of Sales', 20);
insert into users (fio, position, adress_id) values ('Delaney Brokenbrow', 'Occupational Therapist', 11);
insert into users (fio, position, adress_id) values ('Dee dee Shelborne', 'Accounting Assistant II', 12);
insert into users (fio, position, adress_id) values ('Zane Mussettini', 'Analog Circuit Design manager', 13);
insert into users (fio, position, adress_id) values ('Gabbie Franscioni', 'Human Resources Manager', 14);
insert into users (fio, position, adress_id) values ('Lauritz Bowman', 'Teacher', 12);
insert into users (fio, position, adress_id) values ('Sammy Fidell', 'Senior Editor', 36);
insert into users (fio, position, adress_id) values ('Marje Skirvin', 'Chief Design Engineer', 17);
insert into users (fio, position, adress_id) values ('Gisela Challener', 'Teacher', 38);
insert into users (fio, position, adress_id) values ('Abramo Bagger', 'Assistant Professor', 39);
insert into users (fio, position, adress_id) values ('Loleta Sisdey', 'Dentall Hygienist', 21);



 select u.fio,u.position,a.adress_name  from users as u
        inner join adresses as a on u.adress_id=a.adress_id where
        (u.fio ilike '%da%' or u.fio ilike '%ha%' or u.fio ilike '%ga%') 
        and (u.position ilike '%da%' or u.position ilike '%ha%' or u.position ilike '%ga%') 
        and (a.adress_name ilike '%da%' or a.adress_name ilike '%ha%' or a.adress_name ilike '%ga%')